### ISSUE TITLE
How can one provide typeahead datasouce?

### ISSUE THREAD

**Issue by tsega** [comerc/meteor-autoform-typeahead#1]
The documentation does not actually specify how one would provide the datasource. I tried the following but I get error that the source is not given.

``` JavaScript
description: {
        type: String,
        min: 10,
        autoform: {
            type: "typeahead",
            afFieldInput: {
                typeaheadOptions: {},
                typeaheadDatasets: {
                  name: "users",
                  displayKey: "username",
                  source: Meteor.users.find().fetch().map(function(user){ return user.username; })
                }
            }
        }
    }
```

**Comment by comerc** [comment]
It is wrong. You may use [selectOptions](https://github.com/comerc/meteor-autoform-typeahead/blob/master/autoform-typeahead.js#L78) or implement custom substringMatcher, see [examples](https://twitter.github.io/typeahead.js/examples/).

**Comment by comerc** [comment]
Anyway, selectize is best choice. 😃

**Comment by piyushcoader** [comment]
can you please provide an example? can i use selectOption to load data from helpers..

**Comment by abtx** [comment]
how would one define typeaheadDatasets then? I get "Uncaught TypeError: Cannot read property 'length' of undefined" when trying {{> afQuickField name="tags" type="typeahead"}}.

**Comment by comerc** [comment]
Please see example [here](http://autoform.meteor.com/)

**Comment by sean-stanley** [comment]
The example links to the generic autoform playground. Is that what you intended?
