### ISSUE TITLE
Problem with autosave=true and this package. 

### ISSUE THREAD

**Issue by mvgalle** [comerc/meteor-autoform-typeahead#17]
There appears to be a problem with autosave=true and this package. Does this only work for autosave=false in autoform?

**Comment by comerc** [comment]
please give me solution :)

**Comment by mvgalle** [comment]
@comerc this package is really slick and worked when I used autosave=false and had a submit button for my autoForm. I only have 2 fields that are using typeahead feature in my application so I ended up switching out this package for https://atmospherejs.com/sergeyt/typeahead which solved my problem.
