### ISSUE TITLE
autoform 5.x Support

### ISSUE THREAD

**Issue by stachrom** [comerc/meteor-autoform-typeahead#3]
hi comerc

You package is currently not compatible with autoform > 4.0.

meteor add comerc:autoform-typeahead
 => Errors while adding packages:             

While selecting package versions:
error: conflict: constraint aldeed:autoform@4.0.0 is not satisfied by 5.1.0.

A pull request  waiting for aprovel https://github.com/comerc/meteor-autoform-typeahead/pull/2

Regards roman

**Comment by brylie** [comment]
Great work @stachrom! Any idea if/when this will be merged @comerc? I am considering using your package for a project.

**Comment by brylie** [comment]
Does closing this issue indicate that the package is now compatible with Autoform 5.x?

**Comment by brylie** [comment]
I notice a related commit: https://github.com/comerc/meteor-autoform-typeahead/commit/dd2bb91d97d666832164b436b5e248aefcaf7c9f
