### ISSUE TITLE
Is there a demo app / example for this plugin?

### ISSUE THREAD

**Issue by niranjans** [comerc/meteor-autoform-typeahead#5]
I am trying to integrate this with autoform but I am not sure what would the function for the `dataset` look like. I tried to go through the typeahead documents and came across `bloodhound engine`. Is that relevant here and can we use that suggestion engine? If so, could someone please provide some more information.

**Comment by comerc** [comment]
Please see: https://github.com/comerc/meteor-autoform-typeahead/pull/4
